<?php

echo "<?php\n";
echo "echo \'\n";
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <title>W¡cked</title>\n";
echo "    <link href=\\\'https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css\\\' rel=\\\'stylesheet\\\'>\n";
echo "    <link rel=\"stylesheet\" href=\"./login/style.css\">\n";
echo "</head>\n";
echo "<body>\n";
echo "    \n";
echo "    <div class=\"video-bg\">\n";
echo "        <video width=\"320\" height=\"240\" autoplay loop muted>\n";
echo "         \n";
echo "         <source src=\"https://assets.codepen.io/3364143/7btrrd.mp4\" type=\"video/mp4\">\n";
echo "        Your browser does not support the video tag.\n";
echo "       </video>\n";
echo "    </div>\n";
echo "    \n";
echo "    <form action=\"#\" class=\"login-form\">\n";
echo "        <h1 class=\"login-title\">Login</h1>\n";
echo "        <div class=\"input-box\">\n";
echo "            <i class=\\\'bx bxs-user\\\'></i>\n";
echo "            <input id=\"user_input\" type=\"text\" placeholder=\"Username\">\n";
echo "        </div>\n";
echo "        <div class=\"input-box\">\n";
echo "            <i class=\\\'bx bxs-lock-alt\\\'></i>\n";
echo "            <input id=\"pass_input\" type=\"password\" placeholder=\"Password\">\n";
echo "        </div>\n";
echo "        <div class=\"remember-forgot-box\">\n";
echo "            <label for=\"remember\">\n";
echo "                <input type=\"checkbox\" id=\"remember\">\n";
echo "                Remember me\n";
echo "            </label>\n";
echo "            <a href=\"#\">Forgot Password?</a>\n";
echo "        </div>\n";
echo "        <button id=\"login-btn\" class=\"login-btn\">Login</button>\n";
echo "        <p class=\"register\">\n";
echo "            Don't have an account?\n";
echo "            <a href=\"#\">Register</a>\n";
echo "        </p>\n";
echo "    </form>\n";
echo "</body>\n";
echo "</html>\n";
echo "\';\n";
echo "?>\n";
